vich_uploader:
  db_driver: orm

  mappings:
    user_images:
      uri_prefix:         /images/user
      upload_destination: '%kernel.project_dir%/public/images/user'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    speciality_images:
      uri_prefix:         /images/cardSpeciality
      upload_destination: '%kernel.project_dir%/public/images/speciality'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer