controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#specialite card en detail
#Speciality:
#path:  '/Speciality/{specialityName}'
#controller: 'App\Controller\SpecialityController::ShowSpeciality'


#route de mon profile
profile:
    path: /user/profile
    controller: App\Controller\UserController::profile